version: '3.8'

services:
  voto-vigia-api:
    build: .
    container_name: voto_vigia_container
    ports:
      - "8000:8000"
    volumes:
      # Montar modelos y datos para persistencia
      - ./models:/app/models
      - ./data/processed:/app/data/processed
      # Montar la carpeta app para ver cambios en la UI sin reconstruir la imagen
      - ./app:/app/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1